package gui;

import Factory.ConexaoFactory;
import static Factory.ConexaoFactory.con;

import dao.CidadeDAO;
import entity.Cidade;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author helio
 */
public class CadCidade extends javax.swing.JDialog {

    Statement stmt;

    public CadCidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciarBD();

    }

    public CadCidade() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        btprimeiro = new javax.swing.JButton();
        btanterior = new javax.swing.JButton();
        btproximo = new javax.swing.JButton();
        btultimo = new javax.swing.JButton();
        Novo = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        btpesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, -1, -1));

        jLabel2.setText("Cidade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 105, -1, -1));

        jLabel3.setText("Estado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 139, -1, -1));

        tfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(tfcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 44, 163, -1));
        getContentPane().add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 100, 203, -1));

        tfEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(tfEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 134, 302, -1));

        btprimeiro.setText("<<");
        btprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprimeiroActionPerformed(evt);
            }
        });
        getContentPane().add(btprimeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 211, -1, -1));

        btanterior.setText("<");
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 211, -1, -1));

        btproximo.setText(">");
        btproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproximoActionPerformed(evt);
            }
        });
        getContentPane().add(btproximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 211, -1, -1));

        btultimo.setText(">>");
        btultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btultimoActionPerformed(evt);
            }
        });
        getContentPane().add(btultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 211, -1, -1));

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon (1).png"))); // NOI18N
        Novo.setText("Limpar");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        getContentPane().add(Novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/diskette.png"))); // NOI18N
        btsalvar.setText("Gravar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        btexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icon.png"))); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        btpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tool.png"))); // NOI18N
        btpesquisar.setText("Buscar");
        btpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/arrows.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 90, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoActionPerformed

    private void tfEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstadoActionPerformed


    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed

        try {
            int cod = Integer.parseInt(tfcodigo.getText());
            String nomeCidade = tfCidade.getText();
            String nomeEstado = tfEstado.getText();
            
            
            Cidade cidade = new Cidade();

            cidade.setCod(cod);
            cidade.setNomeCidade(nomeCidade);
            cidade.setNomeEstado(nomeEstado);
            
            cidadeDAO.salvarRegistro(cidade);

            JOptionPane.showMessageDialog(this, "Cidade Salva com sucesso");

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }finally{
            limparCampos();
        }


    }//GEN-LAST:event_btsalvarActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed

        limparCampos();


    }//GEN-LAST:event_NovoActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed

        String cod = tfcodigo.getText();

        try {
            cidadeDAO.excluirRegistro(Integer.parseInt(cod));
            JOptionPane.showMessageDialog(this, "Excluindo Info...");

        } catch (SQLException ex) {
            Logger.getLogger(CadCidade.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            limparCampos();
        }

    }//GEN-LAST:event_btexcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        //Fecha a interface gráfica.
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void btpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisarActionPerformed

        int cod = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o código"));

        try {
            Cidade cidade = cidadeDAO.pesquisarCidade(cod);

            if (cidade != null) {
                mostrarDados(cidade);
                JOptionPane.showMessageDialog(this, "Cidade encontrado...");

            } else {
                JOptionPane.showMessageDialog(this, "A cidade não foi encontrado...");

            }

        } catch (SQLException ex) {
            Logger.getLogger(CadCidade.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btpesquisarActionPerformed

    private void btprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprimeiroActionPerformed
        primeiro();

    }//GEN-LAST:event_btprimeiroActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed
        anterior();
    }//GEN-LAST:event_btanteriorActionPerformed

    private void btproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproximoActionPerformed
        proximo();
    }//GEN-LAST:event_btproximoActionPerformed

    private void btultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btultimoActionPerformed

        ultimo();
    }//GEN-LAST:event_btultimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadCidade dialog = new CadCidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Novo;
    private javax.swing.JButton btanterior;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btpesquisar;
    private javax.swing.JButton btprimeiro;
    private javax.swing.JButton btproximo;
    private javax.swing.JButton btsalvar;
    private javax.swing.JButton btultimo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfcodigo;
    // End of variables declaration//GEN-END:variables

    private CidadeDAO cidadeDAO;

    private void iniciarBD() {

        try {

            cidadeDAO = new CidadeDAO();
            
            primeiro();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }

   
    //Atualizar as informações dos campos de texto.
    public void mostrarDados(Cidade cidade) {

       

            tfcodigo.setText(String.valueOf(cidade.getCod()));
            tfCidade.setText(cidade.getNomeCidade());
            tfEstado.setText(cidade.getNomeEstado());

      
    }

    public void primeiro() {

        Cidade cidade;

        try {
            cidade = cidadeDAO.primeiro();

            if (cidade != null) {
                mostrarDados(cidade);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }

    }

    public void anterior() {

        Cidade cidade;

        try {
            cidade = cidadeDAO.anterior();

            if (cidade != null) {
                mostrarDados(cidade);

            } else {
                JOptionPane.showMessageDialog(this, "Primeiro item selecionado");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }

    }

    public void proximo() {

        Cidade cidade;

        try {
            cidade = cidadeDAO.proximo();

            if (cidade != null) {
                mostrarDados(cidade);

            } else {
                JOptionPane.showMessageDialog(this, "Ultimo item selecionado");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }

    }

    public void ultimo() {

        Cidade cidade;

        try {
            cidade = cidadeDAO.ultimo();

            if (cidade != null) {
                mostrarDados(cidade);

            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());

        }

    }

    private void limparCampos() {
   
    //Apaga as informações dos campos de texto da interface gráfica.
        tfcodigo.setText("");
        tfCidade.setText("");
        tfEstado.setText("");

        tfcodigo.requestFocus();
    }

}
